### ISSUE TITLE
Add category Cards

### ISSUE THREAD

**Issue by minawal** [minawal/capstone-project#1]
## Value statement

**As** a user
**I want to** scroll through the cards
**in order to** find the right sport for me

##Description
![User Story 1](https://user-images.githubusercontent.com/77300252/110586591-bd78d680-8172-11eb-8a10-2348077f7fbd.png)

### Acceptance criteria (edge cases)

- [x] all cards are shown by default
- [x] cards are buttons
- [x] contains Icon and title

### Complexity (S,M,L)
S

### Tasks
- [x] Choose sports
- [x] Search for Icons
- [x] Create categoryCard component
- [x] Create categories component
