### ISSUE TITLE
Add event miniCard

### ISSUE THREAD

**Issue by minawal** [minawal/capstone-project#4]
## Value statement

**As** a user
**I want to** scroll through the event miniCards
**in order to** compare the single events and click through the ones I'm interested in

##Description
![User Story 2](https://user-images.githubusercontent.com/77300252/110908731-855aca80-830f-11eb-8fc6-46b8f61a52da.png)

### Acceptance criteria (edge cases)

- [ ] cards are created by available data
- [ ] cards are clickable
- [ ] contains elements as designed
- [ ] participants counter changes 
- [ ] default image by category

### Complexity (S,M,L)
S

### Tasks
- [ ] Choose sports
- [ ] Search for Icons and Images
- [ ] Create miniCard component
- [ ] Create miniCardPage component
- [ ] Create Data
